#eureka:
#  client:
#    serviceUrl:
##      defaultZone: http://54.169.3.140:8761/eureka
#      defaultZone: http://localhost:8761/eureka
#      fetch-registry: true
#      register-with-eureka: true
#  instance:
#    preferIpAddress: true